apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shamzuks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shamzuks 
    spec:
      containers:
        - name: shamzuks 
          image: shamscontainerregistry.azurecr.io/shamzuks
          ports:
          - containerPort: 8080